### ISSUE TITLE
2023 Summer Papers Read List

### ISSUE THREAD

**Issue by cpprhtn** [SUSC-KR/Read-the-papers#1]

**Comment by cpprhtn** [comment]
Example!

읽을 논문 제목: Explanations in Autonomous Driving: A Survey

논문의 arxiv 주소: https://arxiv.org/abs/2103.05154

**Comment by qor6** [comment]
Zeus: Understanding and Optimizing GPU Energy Consumption of DNN Training

https://arxiv.org/abs/2208.06102

**Comment by Seungwon62** [comment]
Semantic-SAM: Segment and Recognize Anything at Any Granularity

https://paperswithcode.com/paper/semantic-sam-segment-and-recognize-anything

**Comment by rnjswn** [comment]
Development of Fake News Model using Machine Learning through Natural Language Processing

https://arxiv.org/abs/2201.07489

**Comment by choo121600** [comment]
NerfDiff: Single-image View Synthesis with NeRF-guided Distillation from 3D-aware Diffusion
arxiv: https://arxiv.org/abs/2302.10109

**Comment by rnjswn** [comment]
Development of Fake News Model using Machine Learning through Natural Language Processing
https://arxiv.org/abs/2201.07489

**Comment by gykwak03** [comment]
Forecasting with Sparse but Informative Variables: A Case Study in Predicting Blood Glucose
https://arxiv.org/abs/2304.08593

**Comment by hemham** [comment]
논문제목:ARviz – An Augmented Reality-enabled Visualization Platform for ROS
Applications
주소: https://arxiv.org/abs/2110.15521

**Comment by cpprhtn** [comment]
논문제목: TVM: An Automated End-to-End Optimizing Compiler for Deep Learning
주소: https://arxiv.org/abs/1802.04799

**Comment by hemham** [comment]
Magic123: One Image to High-Quality 3D Object Generation Using Both 2D and 3D Diffusion Priors
https://arxiv.org/abs/2306.17843

**Comment by rnjswn** [comment]
논문 제목 : Implicit Occupancy Flow Fields for Perception and Prediction in Self-Driving
주소 : https://arxiv.org/abs/2308.01471

**Comment by Seungwon62** [comment]
논문 제목 : h2oGPT: Democratizing Large Language Models
주소 : https://paperswithcode.com/paper/h2ogpt-democratizing-large-language-models
